using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.Experimental.Rendering;

public class ScreenSpaceGlobalIlluminationFeature : ScriptableRendererFeature
{
    [System.Serializable]
    public class SSGISettings
    {
        [Header("Ray March")]
        [Tooltip("Number of diffuse rays evaluated per pixel")]
        [Range(1, 128)]
        public int rayCount = 4;

        [Tooltip("Starting index in the deterministic hemisphere sample sequence")]
        [Range(0, 65535)]
        public int sampleOffset = 0;

        [Tooltip("Maximum number of ray march steps")]
        [Range(1, 256)]
        public int maxSteps = 32;

        [Tooltip("Maximum ray travel distance")]
        [Min(0.1f)]
        public float maxDistance = 4.0f;

        [Tooltip("Geometry thickness for hit detection")]
        [Range(0.001f, 1.0f)]
        public float thickness = 0.1f;

        [Tooltip("View-space offset along the surface normal used to start rays")]
        [Range(0.0f, 0.1f)]
        public float originBias = 0.01f;

        [Tooltip("Use the global HiZ textures generated by HierarchicalZBufferFeature")]
        public bool useHiZTracing = false;

        [Header("Lighting")]
        [Tooltip("Indirect diffuse intensity")]
        [Range(0.0f, 4.0f)]
        public float intensity = 1.0f;

        [Tooltip("Maximum fraction of SSGI mixed into the camera color")]
        [Range(0.0f, 1.0f)]
        public float maxBlend = 0.35f;

        [Header("Blur")]
        [Tooltip("Base edge-aware filter radius in pixels; the second iteration uses twice this radius (0 = no blur)")]
        [Range(0f, 8f)]
        public float blurSpread = 1.5f;

        [Header("Jitter")]
        [Tooltip("Enable jitter dither to reduce regular sampling artifacts")]
        public bool jitterDither = true;

        [Header("Temporal")]
        [Tooltip("Current-frame weight used by the fixed exponential moving average")]
        [Range(0.001f, 1.0f)]
        public float temporalResponse = 0.05f;

        [Tooltip("Minimum linear eye-depth difference that rejects stale per-pixel history")]
        [Min(0.001f)]
        public float temporalDepthThreshold = 0.1f;
    }

    [SerializeField] private SSGISettings settings = new SSGISettings();
    [SerializeField] private Shader ssgiShader;

    private Material ssgiMaterial;
    private ScreenSpaceGlobalIlluminationPass ssgiPass;

    public override void Create()
    {
        ssgiPass = new ScreenSpaceGlobalIlluminationPass(settings);
        ssgiPass.renderPassEvent = RenderPassEvent.BeforeRenderingPostProcessing;
    }

    public override void SetupRenderPasses(ScriptableRenderer renderer, in RenderingData renderingData)
    {
        if (ssgiMaterial == null) return;
        ssgiPass.Setup(ssgiMaterial, settings, renderer.cameraColorTargetHandle);
    }

    public override void AddRenderPasses(ScriptableRenderer renderer, ref RenderingData renderingData)
    {
        if (ssgiShader == null) return;
        if (ssgiMaterial == null)
            ssgiMaterial = CoreUtils.CreateEngineMaterial(ssgiShader);
        if (ssgiMaterial == null) return;
        renderer.EnqueuePass(ssgiPass);
    }

    protected override void Dispose(bool disposing)
    {
        ssgiPass?.Dispose();
        CoreUtils.Destroy(ssgiMaterial);
        ssgiMaterial = null;
    }

    internal class ScreenSpaceGlobalIlluminationPass : ScriptableRenderPass
    {
        private Material material;
        private SSGISettings settings;
        private RTHandle sourceHandle;
        private readonly Dictionary<int, CameraState> cameraStates = new Dictionary<int, CameraState>();
        private const int MaxCameraStates = 4;

        private sealed class CameraState
        {
            public Camera camera;
            public int lastUsedFrame;
            public RenderTextureDescriptor descriptor;
            public bool descriptorValid;
            public bool hasPreviousPose;
            public Vector3 previousPosition;
            public Quaternion previousRotation;
            public bool hasPreviousConfiguration;
            public Matrix4x4 previousProjectionMatrix;
            public int previousSettingsHash;
            public bool historyValid;
            public int historyCount;
            public int sampleOffset;
            public int lastUpdateFrame = -1;
            public int historyReadIndex;
            public RTHandle radianceRT;
            public RTHandle blurA;
            public RTHandle blurB;
            public RTHandle historyA;
            public RTHandle historyB;
            public RTHandle compositeRT;

            public RTHandle HistoryRead => historyReadIndex == 0 ? historyA : historyB;
            public RTHandle HistoryWrite => historyReadIndex == 0 ? historyB : historyA;

            public void Release()
            {
                radianceRT?.Release();
                blurA?.Release();
                blurB?.Release();
                historyA?.Release();
                historyB?.Release();
                compositeRT?.Release();
                radianceRT = null;
                blurA = null;
                blurB = null;
                historyA = null;
                historyB = null;
                compositeRT = null;
            }
        }

        private static readonly ProfilingSampler profilingSampler =
            new ProfilingSampler("Screen Space Global Illumination");

        private static readonly int UVToViewPosID = Shader.PropertyToID("_UVToViewPos");
        private static readonly int RayCountID = Shader.PropertyToID("_SSGIRayCount");
        private static readonly int SampleOffsetID = Shader.PropertyToID("_SSGISampleOffset");
        private static readonly int MaxStepsID = Shader.PropertyToID("_SSGIMaxSteps");
        private static readonly int MaxDistanceID = Shader.PropertyToID("_SSGIMaxDistance");
        private static readonly int ThicknessID = Shader.PropertyToID("_SSGIThickness");
        private static readonly int OriginBiasID = Shader.PropertyToID("_SSGIOriginBias");
        private static readonly int IntensityID = Shader.PropertyToID("_SSGIIntensity");
        private static readonly int MaxBlendID = Shader.PropertyToID("_SSGIMaxBlend");
        private static readonly int BlurSpreadID = Shader.PropertyToID("_BlurSpread");
        private static readonly int RadianceTextureID = Shader.PropertyToID("_SSGIRadianceTexture");
        private static readonly int HistoryTextureID = Shader.PropertyToID("_SSGIHistoryTexture");
        private static readonly int HistoryValidID = Shader.PropertyToID("_SSGIHistoryValid");
        private static readonly int HistoryWeightID = Shader.PropertyToID("_SSGIHistoryWeight");
        private static readonly int HistoryDepthThresholdID = Shader.PropertyToID("_SSGIHistoryDepthThreshold");
        private static readonly int OriginalTextureID = Shader.PropertyToID("_OriginalTexture");
        private const string JitterKeyword = "_JITTER_ON";
        private const string HiZKeyword = "_SSGI_HIZ_ON";

        public ScreenSpaceGlobalIlluminationPass(SSGISettings settings)
        {
            this.settings = settings;
        }

        public void Setup(Material mat, SSGISettings ssgiSettings, RTHandle source)
        {
            material = mat;
            settings = ssgiSettings;
            sourceHandle = source;
            ConfigureInput(ScriptableRenderPassInput.Depth | ScriptableRenderPassInput.Color);
        }

        public override void OnCameraSetup(CommandBuffer cmd, ref RenderingData renderingData)
        {
            Camera camera = renderingData.cameraData.camera;
            int cameraId = camera.GetInstanceID();
            bool hasState = cameraStates.TryGetValue(cameraId, out CameraState state);
            if (hasState && (state.camera == null || state.camera != camera))
            {
                state.Release();
                cameraStates.Remove(cameraId);
                hasState = false;
            }

            if (!hasState)
            {
                RetireCameraStates(cameraId);
                state = new CameraState { camera = camera };
                cameraStates.Add(cameraId, state);
            }
            state.lastUsedFrame = Time.frameCount;

            var desc = renderingData.cameraData.cameraTargetDescriptor;
            desc.depthBufferBits = 0;
            desc.msaaSamples = 1;
            desc.graphicsFormat = GraphicsFormat.R16G16B16A16_SFloat;

            bool descriptorChanged = !state.descriptorValid || !state.descriptor.Equals(desc);
            if (descriptorChanged)
            {
                state.descriptor = desc;
                state.descriptorValid = true;
                ResetTemporalState(state);
            }

            string suffix = cameraId.ToString();
            RenderingUtils.ReAllocateIfNeeded(ref state.radianceRT, desc, FilterMode.Bilinear, TextureWrapMode.Clamp, name: "_SSGI_Radiance_" + suffix);
            RenderingUtils.ReAllocateIfNeeded(ref state.blurA, desc, FilterMode.Bilinear, TextureWrapMode.Clamp, name: "_SSGI_BlurA_" + suffix);
            RenderingUtils.ReAllocateIfNeeded(ref state.blurB, desc, FilterMode.Bilinear, TextureWrapMode.Clamp, name: "_SSGI_BlurB_" + suffix);
            RenderingUtils.ReAllocateIfNeeded(ref state.historyA, desc, FilterMode.Bilinear, TextureWrapMode.Clamp, name: "_SSGI_HistoryA_" + suffix);
            RenderingUtils.ReAllocateIfNeeded(ref state.historyB, desc, FilterMode.Bilinear, TextureWrapMode.Clamp, name: "_SSGI_HistoryB_" + suffix);
            RenderingUtils.ReAllocateIfNeeded(ref state.compositeRT, desc, FilterMode.Bilinear, TextureWrapMode.Clamp, name: "_SSGI_Composite_" + suffix);
        }

        public override void Execute(ScriptableRenderContext context, ref RenderingData renderingData)
        {
            if (material == null) return;

            Camera cam = renderingData.cameraData.camera;
            if (!cameraStates.TryGetValue(cam.GetInstanceID(), out CameraState state)) return;
            if (state.camera == null || state.camera != cam) return;
            state.lastUsedFrame = Time.frameCount;

            CommandBuffer cmd = CommandBufferPool.Get("SSGI Pass");
            bool isNewLogicalFrame = state.lastUpdateFrame != Time.frameCount;
            bool poseChanged = !state.hasPreviousPose ||
                state.previousPosition != cam.transform.position ||
                state.previousRotation != cam.transform.rotation;
            Matrix4x4 projectionMatrix = cam.nonJitteredProjectionMatrix;
            int settingsHash = ComputeSettingsHash(settings);
            bool configurationChanged = !state.hasPreviousConfiguration ||
                state.previousProjectionMatrix != projectionMatrix ||
                state.previousSettingsHash != settingsHash;
            int rayCount = Mathf.Clamp(settings.rayCount, 1, 128);
            int baseSampleOffset = Mathf.Clamp(settings.sampleOffset, 0, 65535);

            bool resetHistory = poseChanged || configurationChanged;
            if (resetHistory)
                ResetTemporalState(state);

            bool accumulate = resetHistory || isNewLogicalFrame;
            if (accumulate)
            {
                if (!resetHistory && state.historyValid)
                    state.sampleOffset = (state.sampleOffset + rayCount) & 0xFFFF;
                else
                    state.sampleOffset = baseSampleOffset;
            }

            using (new ProfilingScope(cmd, profilingSampler))
            {
                float farClip = Mathf.Max(cam.farClipPlane, 0.1f);
                float maxDistance = IsFinite(settings.maxDistance)
                    ? Mathf.Clamp(settings.maxDistance, 0.1f, farClip)
                    : Mathf.Min(4.0f, farClip);
                float thickness = IsFinite(settings.thickness)
                    ? Mathf.Clamp(settings.thickness, 0.001f, 1.0f)
                    : 0.1f;
                float originBias = IsFinite(settings.originBias)
                    ? Mathf.Clamp(settings.originBias, 0.0f, 0.1f)
                    : 0.01f;
                float intensity = IsFinite(settings.intensity)
                    ? Mathf.Clamp(settings.intensity, 0.0f, 4.0f)
                    : 1.0f;
                float maxBlend = IsFinite(settings.maxBlend)
                    ? Mathf.Clamp01(settings.maxBlend)
                    : 0.35f;
                float blurSpread = IsFinite(settings.blurSpread)
                    ? Mathf.Clamp(settings.blurSpread, 0.0f, 8.0f)
                    : 1.5f;
                float temporalResponse = IsFinite(settings.temporalResponse)
                    ? Mathf.Clamp(settings.temporalResponse, 0.001f, 1.0f)
                    : 0.05f;
                float temporalDepthThreshold = IsFinite(settings.temporalDepthThreshold)
                    ? Mathf.Max(settings.temporalDepthThreshold, 0.001f)
                    : 0.1f;

                material.SetVector(UVToViewPosID, GIUtility.ComputeUVToViewPos(cam));
                material.SetInt(RayCountID, rayCount);
                material.SetInt(SampleOffsetID, state.sampleOffset);
                material.SetInt(MaxStepsID, Mathf.Clamp(settings.maxSteps, 1, 256));
                material.SetFloat(MaxDistanceID, maxDistance);
                material.SetFloat(ThicknessID, thickness);
                material.SetFloat(OriginBiasID, originBias);
                material.SetFloat(IntensityID, intensity);
                material.SetFloat(MaxBlendID, maxBlend);
                material.SetFloat(BlurSpreadID, blurSpread);
                material.SetFloat(HistoryDepthThresholdID, temporalDepthThreshold);

                if (settings.jitterDither)
                    material.EnableKeyword(JitterKeyword);
                else
                    material.DisableKeyword(JitterKeyword);

                if (settings.useHiZTracing)
                    material.EnableKeyword(HiZKeyword);
                else
                    material.DisableKeyword(HiZKeyword);

                cmd.SetGlobalTexture(OriginalTextureID, sourceHandle);
                if (accumulate)
                {
                    Blitter.BlitCameraTexture(cmd, sourceHandle, state.radianceRT);
                    cmd.SetGlobalTexture(RadianceTextureID, state.radianceRT);

                    Blitter.BlitCameraTexture(cmd, sourceHandle, state.blurA, material, 0);
                    cmd.SetGlobalTexture(HistoryTextureID, state.HistoryRead);
                    material.SetFloat(HistoryValidID, state.historyValid ? 1.0f : 0.0f);
                    material.SetFloat(HistoryWeightID, temporalResponse);
                    Blitter.BlitCameraTexture(cmd, state.blurA, state.HistoryWrite, material, 3);
                    Blitter.BlitCameraTexture(cmd, state.HistoryWrite, state.blurB, material, 1);
                    Blitter.BlitCameraTexture(cmd, state.blurB, state.blurA, material, 2);
                    Blitter.BlitCameraTexture(cmd, state.blurA, state.compositeRT, material, 4);
                }
                else
                {
                    Blitter.BlitCameraTexture(cmd, state.HistoryRead, state.blurB, material, 1);
                    Blitter.BlitCameraTexture(cmd, state.blurB, state.blurA, material, 2);
                    Blitter.BlitCameraTexture(cmd, state.blurA, state.compositeRT, material, 4);
                }

                Blitter.BlitCameraTexture(cmd, state.compositeRT, sourceHandle);
            }

            context.ExecuteCommandBuffer(cmd);
            CommandBufferPool.Release(cmd);

            if (accumulate)
            {
                state.historyReadIndex = 1 - state.historyReadIndex;
                if (state.historyCount < int.MaxValue)
                    state.historyCount++;
                state.historyValid = true;
                state.hasPreviousPose = true;
                state.previousPosition = cam.transform.position;
                state.previousRotation = cam.transform.rotation;
                state.hasPreviousConfiguration = true;
                state.previousProjectionMatrix = projectionMatrix;
                state.previousSettingsHash = settingsHash;
                state.lastUpdateFrame = Time.frameCount;
            }
        }

        private static void ResetTemporalState(CameraState state)
        {
            state.hasPreviousPose = false;
            state.hasPreviousConfiguration = false;
            state.historyValid = false;
            state.historyCount = 0;
            state.sampleOffset = 0;
            state.lastUpdateFrame = -1;
            state.historyReadIndex = 0;
        }

        private void RetireCameraStates(int currentCameraId)
        {
            List<int> retiredIds = new List<int>();
            foreach (KeyValuePair<int, CameraState> pair in cameraStates)
            {
                if (pair.Key != currentCameraId && pair.Value.camera == null)
                {
                    pair.Value.Release();
                    retiredIds.Add(pair.Key);
                }
            }

            foreach (int retiredId in retiredIds)
                cameraStates.Remove(retiredId);

            while (cameraStates.Count >= MaxCameraStates)
            {
                int leastRecentlyUsedId = 0;
                CameraState leastRecentlyUsed = null;
                foreach (KeyValuePair<int, CameraState> pair in cameraStates)
                {
                    if (pair.Key == currentCameraId)
                        continue;
                    if (leastRecentlyUsed == null || pair.Value.lastUsedFrame < leastRecentlyUsed.lastUsedFrame)
                    {
                        leastRecentlyUsedId = pair.Key;
                        leastRecentlyUsed = pair.Value;
                    }
                }

                if (leastRecentlyUsed == null)
                    break;

                leastRecentlyUsed.Release();
                cameraStates.Remove(leastRecentlyUsedId);
            }
        }

        private static bool IsFinite(float value)
        {
            return !float.IsNaN(value) && !float.IsInfinity(value);
        }

        private static int ComputeSettingsHash(SSGISettings value)
        {
            unchecked
            {
                int hash = 17;
                hash = hash * 31 + value.rayCount;
                hash = hash * 31 + value.sampleOffset;
                hash = hash * 31 + value.maxSteps;
                hash = hash * 31 + value.maxDistance.GetHashCode();
                hash = hash * 31 + value.thickness.GetHashCode();
                hash = hash * 31 + value.originBias.GetHashCode();
                hash = hash * 31 + (value.useHiZTracing ? 1 : 0);
                hash = hash * 31 + value.intensity.GetHashCode();
                hash = hash * 31 + value.maxBlend.GetHashCode();
                hash = hash * 31 + value.blurSpread.GetHashCode();
                hash = hash * 31 + (value.jitterDither ? 1 : 0);
                hash = hash * 31 + value.temporalResponse.GetHashCode();
                hash = hash * 31 + value.temporalDepthThreshold.GetHashCode();
                return hash;
            }
        }

        public override void OnCameraCleanup(CommandBuffer cmd)
        {
        }

        public void Dispose()
        {
            foreach (CameraState state in cameraStates.Values)
                state.Release();
            cameraStates.Clear();
        }
    }
}
