using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.Experimental.Rendering;

public class ScreenSpaceGlobalIlluminationFeature : ScriptableRendererFeature
{
    [System.Serializable]
    public class SSGISettings
    {
        [Header("Ray March")]
        [Tooltip("Number of diffuse rays evaluated per pixel")]
        [Range(1, 128)]
        public int rayCount = 4;

        [Tooltip("Starting index in the deterministic hemisphere sample sequence")]
        [Range(0, 65535)]
        public int sampleOffset = 0;

        [Tooltip("Maximum number of ray march steps")]
        [Range(1, 2048)]
        public int maxSteps = 32;

        [Tooltip("Maximum ray travel distance")]
        [Min(0.1f)]
        public float maxDistance = 4.0f;

        [Tooltip("Geometry thickness for hit detection")]
        [Range(0.001f, 1.0f)]
        public float thickness = 0.1f;

        [Tooltip("View-space offset along the surface normal used to prevent rays from intersecting their source surface")]
        [Range(0.0f, 0.1f)]
        public float originBias = 0.01f;

        [Tooltip("Use the global HiZ textures generated by HierarchicalZBufferFeature")]
        public bool useHiZTracing = false;

        [Header("Lighting")]
        [Tooltip("Indirect diffuse intensity")]
        [Range(0.0f, 4.0f)]
        public float intensity = 1.0f;

        [Header("Blur")]
        [Tooltip("Base edge-aware filter radius in pixels; the second iteration uses twice this radius (0 = no blur)")]
        [Range(0f, 8f)]
        public float blurSpread = 1.5f;

        [Header("Jitter")]
        [Tooltip("Enable jitter dither to reduce regular sampling artifacts")]
        public bool jitterDither = true;

        [Header("Temporal")]
        [Tooltip("Current-frame weight used after a pixel reaches the temporal accumulation cap")]
        [Range(0.001f, 1.0f)]
        public float temporalResponse = 0.08f;

        [Tooltip("Maximum number of Monte Carlo frames accumulated per pixel before switching to the fixed temporal response")]
        [Range(2, 2048)]
        public int maxHistoryFrames = 8;

        [Tooltip("Minimum linear eye-depth difference that rejects stale per-pixel history")]
        [Min(0.001f)]
        public float temporalDepthThreshold = 0.1f;

        [Tooltip("Low-confidence previous-frame irradiance used to hide newly disoccluded black regions")]
        [Range(0.0f, 1.0f)]
        public float disocclusionFallback = 0.35f;

        [Header("Resolution")]
        [Tooltip("Run the SSGI trace, blur and temporal passes at half resolution and upscale in the Combine pass (UnitySSGIURP style)")]
        public bool halfResolution = true;

        [Header("Sampling")]
        [Tooltip("Hemisphere RNG used by the trace pass. R2 keeps the legacy low-discrepancy sequence; Hash matches UnitySSGIURP's hash + frame-counter generator")]
        public SSGIRngMode rngMode = SSGIRngMode.R2;

    }

    public enum SSGIRngMode
    {
        R2 = 0,
        Hash = 1,
    }

    [SerializeField] private SSGISettings settings = new SSGISettings();
    [SerializeField] private Shader ssgiShader;

    private Material ssgiMaterial;
    private IrradianceHistorySetupPass irradianceHistorySetupPass;
    private ForwardGBufferPass forwardGBufferPass;
    private ScreenSpaceGlobalIlluminationPass ssgiPass;

    public override void Create()
    {
        ssgiPass = new ScreenSpaceGlobalIlluminationPass(settings);
        ssgiPass.renderPassEvent = RenderPassEvent.BeforeRenderingPostProcessing;
        irradianceHistorySetupPass = new IrradianceHistorySetupPass(ssgiPass);
        irradianceHistorySetupPass.renderPassEvent = RenderPassEvent.BeforeRenderingOpaques;
        forwardGBufferPass = new ForwardGBufferPass();
        forwardGBufferPass.renderPassEvent = RenderPassEvent.AfterRenderingOpaques;
    }

    public override void SetupRenderPasses(ScriptableRenderer renderer, in RenderingData renderingData)
    {
        if (ssgiMaterial == null) return;
        ssgiPass.Setup(ssgiMaterial, settings, renderer.cameraColorTargetHandle);
    }

    public override void AddRenderPasses(ScriptableRenderer renderer, ref RenderingData renderingData)
    {
        if (ssgiShader == null) return;
        if (ssgiMaterial == null)
            ssgiMaterial = CoreUtils.CreateEngineMaterial(ssgiShader);
        if (ssgiMaterial == null) return;
        renderer.EnqueuePass(irradianceHistorySetupPass);
        renderer.EnqueuePass(forwardGBufferPass);
        renderer.EnqueuePass(ssgiPass);
    }

    protected override void Dispose(bool disposing)
    {
        forwardGBufferPass?.Dispose();
        ssgiPass?.Dispose();
        CoreUtils.Destroy(ssgiMaterial);
        ssgiMaterial = null;
    }

    internal class ForwardGBufferPass : ScriptableRenderPass
    {
        private const string ProfilerTag = "SSGI Forward GBuffer";
        private const string AlbedoTextureName = "_SSGIGBufferAlbedo";
        private const string MaterialTextureName = "_SSGIGBufferMaterial";
        private const string NormalTextureName = "_SSGIGBufferNormalWS";
        private const string PositionTextureName = "_SSGIGBufferPositionWS";
        private const string DepthTextureName = "_SSGIGBufferDepth";

        private static readonly ShaderTagId ForwardGBufferShaderTag =
            new ShaderTagId("SSGIForwardGBuffer");
        private static readonly ProfilingSampler ProfilingSampler =
            new ProfilingSampler(ProfilerTag);
        private static readonly int AlbedoTextureID = Shader.PropertyToID(AlbedoTextureName);
        private static readonly int MaterialTextureID = Shader.PropertyToID(MaterialTextureName);
        private static readonly int NormalTextureID = Shader.PropertyToID(NormalTextureName);
        private static readonly int PositionTextureID = Shader.PropertyToID(PositionTextureName);

        private FilteringSettings filteringSettings =
            new FilteringSettings(RenderQueueRange.opaque);
        private RenderStateBlock renderStateBlock =
            new RenderStateBlock(RenderStateMask.Depth);
        private readonly RTHandle[] gbufferAttachments = new RTHandle[4];

        private RTHandle albedoTexture;
        private RTHandle materialTexture;
        private RTHandle normalTexture;
        private RTHandle positionTexture;
        private RTHandle depthTexture;

        public ForwardGBufferPass()
        {
            ConfigureInput(ScriptableRenderPassInput.Depth);
        }

        public override void OnCameraSetup(CommandBuffer cmd, ref RenderingData renderingData)
        {
            RenderTextureDescriptor descriptor = renderingData.cameraData.cameraTargetDescriptor;
            descriptor.depthBufferBits = 0;
            descriptor.stencilFormat = GraphicsFormat.None;
            descriptor.msaaSamples = 1;
            descriptor.bindMS = false;

            descriptor.graphicsFormat = QualitySettings.activeColorSpace == ColorSpace.Linear
                ? GraphicsFormat.R8G8B8A8_SRGB
                : GraphicsFormat.R8G8B8A8_UNorm;
            RenderingUtils.ReAllocateIfNeeded(
                ref albedoTexture, descriptor, FilterMode.Point, TextureWrapMode.Clamp,
                name: AlbedoTextureName);

            descriptor.graphicsFormat = GraphicsFormat.R8G8B8A8_UNorm;
            RenderingUtils.ReAllocateIfNeeded(
                ref materialTexture, descriptor, FilterMode.Point, TextureWrapMode.Clamp,
                name: MaterialTextureName);

            descriptor.graphicsFormat = GraphicsFormat.R16G16B16A16_SFloat;
            RenderingUtils.ReAllocateIfNeeded(
                ref normalTexture, descriptor, FilterMode.Point, TextureWrapMode.Clamp,
                name: NormalTextureName);
            RenderingUtils.ReAllocateIfNeeded(
                ref positionTexture, descriptor, FilterMode.Point, TextureWrapMode.Clamp,
                name: PositionTextureName);

            gbufferAttachments[0] = albedoTexture;
            gbufferAttachments[1] = materialTexture;
            gbufferAttachments[2] = normalTexture;
            gbufferAttachments[3] = positionTexture;

            cmd.SetGlobalTexture(AlbedoTextureID, albedoTexture);
            cmd.SetGlobalTexture(MaterialTextureID, materialTexture);
            cmd.SetGlobalTexture(NormalTextureID, normalTexture);
            cmd.SetGlobalTexture(PositionTextureID, positionTexture);

            bool isOpenGL =
                SystemInfo.graphicsDeviceType == GraphicsDeviceType.OpenGLES3 ||
                SystemInfo.graphicsDeviceType == GraphicsDeviceType.OpenGLCore;
            bool canReuseCameraDepth =
                !isOpenGL &&
                (renderingData.cameraData.renderType == CameraRenderType.Base ||
                 renderingData.cameraData.clearDepth) &&
                renderingData.cameraData.cameraTargetDescriptor.msaaSamples == descriptor.msaaSamples;

            if (canReuseCameraDepth)
            {
                ConfigureTarget(
                    gbufferAttachments,
                    renderingData.cameraData.renderer.cameraDepthTargetHandle);
                ConfigureClear(ClearFlag.Color, Color.clear);
                renderStateBlock.depthState = new DepthState(false, CompareFunction.Equal);
            }
            else
            {
                RenderTextureDescriptor depthDescriptor =
                    renderingData.cameraData.cameraTargetDescriptor;
                depthDescriptor.msaaSamples = 1;
                depthDescriptor.bindMS = false;
                depthDescriptor.graphicsFormat = GraphicsFormat.None;
                RenderingUtils.ReAllocateIfNeeded(
                    ref depthTexture, depthDescriptor, FilterMode.Point, TextureWrapMode.Clamp,
                    name: DepthTextureName);

                ConfigureTarget(gbufferAttachments, depthTexture);
                ConfigureClear(ClearFlag.Color | ClearFlag.Depth, Color.clear);
                renderStateBlock.depthState = new DepthState(true, CompareFunction.LessEqual);
            }
        }

        public override void Execute(
            ScriptableRenderContext context,
            ref RenderingData renderingData)
        {
            SortingCriteria sortingCriteria =
                renderingData.cameraData.defaultOpaqueSortFlags;
            DrawingSettings drawingSettings = CreateDrawingSettings(
                ForwardGBufferShaderTag,
                ref renderingData,
                sortingCriteria);

            CommandBuffer cmd = CommandBufferPool.Get(ProfilerTag);
            using (new ProfilingScope(cmd, ProfilingSampler))
            {
                context.ExecuteCommandBuffer(cmd);
                cmd.Clear();
                context.DrawRenderers(
                    renderingData.cullResults,
                    ref drawingSettings,
                    ref filteringSettings,
                    ref renderStateBlock);
            }

            context.ExecuteCommandBuffer(cmd);
            CommandBufferPool.Release(cmd);
        }

        public override void OnCameraCleanup(CommandBuffer cmd)
        {
        }

        public void Dispose()
        {
            albedoTexture?.Release();
            materialTexture?.Release();
            normalTexture?.Release();
            positionTexture?.Release();
            depthTexture?.Release();
            albedoTexture = null;
            materialTexture = null;
            normalTexture = null;
            positionTexture = null;
            depthTexture = null;
        }
    }

    internal class IrradianceHistorySetupPass : ScriptableRenderPass
    {
        private readonly ScreenSpaceGlobalIlluminationPass ssgiPass;

        public IrradianceHistorySetupPass(ScreenSpaceGlobalIlluminationPass ssgiPass)
        {
            this.ssgiPass = ssgiPass;
        }

        public override void OnCameraSetup(CommandBuffer cmd, ref RenderingData renderingData)
        {
            ssgiPass.PrepareCamera(ref renderingData);
        }

        public override void Execute(ScriptableRenderContext context, ref RenderingData renderingData)
        {
            CommandBuffer cmd = CommandBufferPool.Get("SSGI Irradiance History Setup");
            ssgiPass.BindPreviousIrradiance(cmd, ref renderingData);
            context.ExecuteCommandBuffer(cmd);
            CommandBufferPool.Release(cmd);
        }
    }

    internal class ScreenSpaceGlobalIlluminationPass : ScriptableRenderPass
    {
        private Material material;
        private SSGISettings settings;
        private RTHandle sourceHandle;
        private readonly Dictionary<int, CameraState> cameraStates = new Dictionary<int, CameraState>();
        private const int MaxCameraStates = 4;
        private const int TemporalAlgorithmVersion = 14;

        private sealed class CameraState
        {
            public Camera camera;
            public int lastUsedFrame;
            public RenderTextureDescriptor descriptor;
            public bool descriptorValid;
            public bool hasPreviousPose;
            public Vector3 previousPosition;
            public Quaternion previousRotation;
            public bool hasPreviousConfiguration;
            public Matrix4x4 previousProjectionMatrix;
            public Matrix4x4 previousViewProjectionMatrix;
            public Matrix4x4 previousWorldToCameraMatrix;
            public int previousSettingsHash;
            public bool historyValid;
            public int sampleOffset;
            public int lastUpdateFrame = -1;
            public int historyReadIndex;
            public RTHandle radianceRT;
            public RTHandle currentIrradianceRT;
            public RTHandle blurA;
            public RTHandle blurB;
            public RTHandle historyA;
            public RTHandle historyB;
            public RTHandle historySampleA;
            public RTHandle historySampleB;
            public RTHandle applyRT;

            public RTHandle HistoryRead => historyReadIndex == 0 ? historyA : historyB;
            public RTHandle HistoryWrite => historyReadIndex == 0 ? historyB : historyA;
            public RTHandle HistorySampleRead =>
                historyReadIndex == 0 ? historySampleA : historySampleB;
            public RTHandle HistorySampleWrite =>
                historyReadIndex == 0 ? historySampleB : historySampleA;

            public void Release()
            {
                radianceRT?.Release();
                currentIrradianceRT?.Release();
                blurA?.Release();
                blurB?.Release();
                historyA?.Release();
                historyB?.Release();
                historySampleA?.Release();
                historySampleB?.Release();
                applyRT?.Release();
                radianceRT = null;
                currentIrradianceRT = null;
                blurA = null;
                blurB = null;
                historyA = null;
                historyB = null;
                historySampleA = null;
                historySampleB = null;
                applyRT = null;
            }
        }

        private static readonly ProfilingSampler ssgiProfilingSampler =
            new ProfilingSampler("Screen Space Global Illumination");

        private static readonly int UVToViewPosID = Shader.PropertyToID("_UVToViewPos");
        private static readonly int RayCountID = Shader.PropertyToID("_SSGIRayCount");
        private static readonly int SampleOffsetID = Shader.PropertyToID("_SSGISampleOffset");
        private static readonly int MaxStepsID = Shader.PropertyToID("_SSGIMaxSteps");
        private static readonly int MaxDistanceID = Shader.PropertyToID("_SSGIMaxDistance");
        private static readonly int ThicknessID = Shader.PropertyToID("_SSGIThickness");
        private static readonly int OriginBiasID = Shader.PropertyToID("_SSGIOriginBias");
        private static readonly int IntensityID = Shader.PropertyToID("_SSGIIntensity");
        private static readonly int BlurSpreadID = Shader.PropertyToID("_BlurSpread");
        private static readonly int RadianceTextureID = Shader.PropertyToID("_SSGIRadianceTexture");
        private static readonly int IrradianceTextureID = Shader.PropertyToID("_SSGIIrradianceTexture");
        private static readonly int PreviousIrradianceValidID =
            Shader.PropertyToID("_SSGIPreviousIrradianceValid");
        private static readonly int IrradianceValidID = Shader.PropertyToID("_SSGIIrradianceValid");
        private static readonly int ReprojectIrradianceID = Shader.PropertyToID("_SSGIReprojectIrradiance");
        private static readonly int DisocclusionFallbackID = Shader.PropertyToID("_SSGIDisocclusionFallback");
        private static readonly int HistoryTextureID = Shader.PropertyToID("_SSGIHistoryTexture");
        private static readonly int HistorySampleTextureID =
            Shader.PropertyToID("_SSGIHistorySampleTexture");
        private static readonly int HistoryValidID = Shader.PropertyToID("_SSGIHistoryValid");
        private static readonly int HistoryWeightID = Shader.PropertyToID("_SSGIHistoryWeight");
        private static readonly int MaxHistoryFramesID =
            Shader.PropertyToID("_SSGIMaxHistoryFrames");
        private static readonly int HistoryDepthThresholdID = Shader.PropertyToID("_SSGIHistoryDepthThreshold");
        private static readonly int PreviousViewProjectionMatrixID = Shader.PropertyToID("_SSGIPreviousViewProjectionMatrix");
        private static readonly int PreviousWorldToCameraMatrixID = Shader.PropertyToID("_SSGIPreviousWorldToCameraMatrix");
        private static readonly int IrradianceTexelSizeID = Shader.PropertyToID("_SSGIIrradianceTexture_TexelSize");
        private static readonly int TraceSizeID = Shader.PropertyToID("_SSGITraceSize");
        private static readonly int HalfResolutionID = Shader.PropertyToID("_SSGIHalfResolution");
        private static readonly int RngFrameIndexID = Shader.PropertyToID("_SSGIRngFrameIndex");
        private static readonly int RngSeedID = Shader.PropertyToID("_SSGIRngSeed");
        private const string JitterKeyword = "_JITTER_ON";
        private const string HiZKeyword = "_SSGI_HIZ_ON";
        private const string RngHashKeyword = "_SSGI_RNG_HASH";

        public ScreenSpaceGlobalIlluminationPass(SSGISettings settings)
        {
            this.settings = settings;
        }

        public void Setup(Material mat, SSGISettings ssgiSettings, RTHandle source)
        {
            material = mat;
            settings = ssgiSettings;
            sourceHandle = source;
            ConfigureInput(
                ScriptableRenderPassInput.Depth |
                ScriptableRenderPassInput.Color |
                ScriptableRenderPassInput.Motion);
        }

        public override void OnCameraSetup(CommandBuffer cmd, ref RenderingData renderingData)
        {
            PrepareCamera(ref renderingData);
        }

        public void PrepareCamera(ref RenderingData renderingData)
        {
            Camera camera = renderingData.cameraData.camera;
            int cameraId = camera.GetInstanceID();
            bool hasState = cameraStates.TryGetValue(cameraId, out CameraState state);
            if (hasState && (state.camera == null || state.camera != camera))
            {
                state.Release();
                cameraStates.Remove(cameraId);
                hasState = false;
            }

            if (!hasState)
            {
                RetireCameraStates(cameraId);
                state = new CameraState { camera = camera };
                cameraStates.Add(cameraId, state);
            }
            state.lastUsedFrame = Time.frameCount;

            var desc = renderingData.cameraData.cameraTargetDescriptor;
            desc.depthBufferBits = 0;
            desc.msaaSamples = 1;
            desc.graphicsFormat = GraphicsFormat.R16G16B16A16_SFloat;

            // Half-resolution descriptor used by every SSGI working texture
            // when halfResolution is enabled. UVs are normalised so the half-res
            // passes can still sample the full-res G-buffer/depth textures
            // without any extra coordinate munging.
            var traceDesc = desc;
            if (settings.halfResolution)
            {
                traceDesc.width = Mathf.Max(1, desc.width / 2);
                traceDesc.height = Mathf.Max(1, desc.height / 2);
            }

            bool descriptorChanged = !state.descriptorValid || !state.descriptor.Equals(desc);
            if (descriptorChanged)
            {
                state.descriptor = desc;
                state.descriptorValid = true;
                ResetTemporalState(state);
            }

            string suffix = cameraId.ToString();
            RenderingUtils.ReAllocateIfNeeded(ref state.radianceRT, traceDesc, FilterMode.Bilinear, TextureWrapMode.Clamp, name: "_SSGI_Radiance_" + suffix);
            RenderingUtils.ReAllocateIfNeeded(ref state.currentIrradianceRT, traceDesc, FilterMode.Bilinear, TextureWrapMode.Clamp, name: "_SSGI_CurrentIrradiance_" + suffix);
            RenderingUtils.ReAllocateIfNeeded(ref state.blurA, traceDesc, FilterMode.Bilinear, TextureWrapMode.Clamp, name: "_SSGI_BlurA_" + suffix);
            RenderingUtils.ReAllocateIfNeeded(ref state.blurB, traceDesc, FilterMode.Bilinear, TextureWrapMode.Clamp, name: "_SSGI_BlurB_" + suffix);
            RenderingUtils.ReAllocateIfNeeded(ref state.historyA, traceDesc, FilterMode.Bilinear, TextureWrapMode.Clamp, name: "_SSGI_HistoryA_" + suffix);
            RenderingUtils.ReAllocateIfNeeded(ref state.historyB, traceDesc, FilterMode.Bilinear, TextureWrapMode.Clamp, name: "_SSGI_HistoryB_" + suffix);

            var sampleCountDesc = traceDesc;
            sampleCountDesc.graphicsFormat = GraphicsFormat.R16_SFloat;
            RenderingUtils.ReAllocateIfNeeded(ref state.historySampleA, sampleCountDesc, FilterMode.Point, TextureWrapMode.Clamp, name: "_SSGI_HistorySampleA_" + suffix);
            RenderingUtils.ReAllocateIfNeeded(ref state.historySampleB, sampleCountDesc, FilterMode.Point, TextureWrapMode.Clamp, name: "_SSGI_HistorySampleB_" + suffix);

            // applyRT is full resolution because Combine writes camera color.
            RenderingUtils.ReAllocateIfNeeded(ref state.applyRT, desc, FilterMode.Bilinear, TextureWrapMode.Clamp, name: "_SSGI_Apply_" + suffix);
        }

        public void BindPreviousIrradiance(CommandBuffer cmd, ref RenderingData renderingData)
        {
            Camera cam = renderingData.cameraData.camera;
            if (!cameraStates.TryGetValue(cam.GetInstanceID(), out CameraState state))
            {
                cmd.SetGlobalFloat(IrradianceValidID, 0.0f);
                return;
            }

            // Composite is the only place that applies indirect lighting.
            // Clear the previous frame binding before opaque objects render so
            // legacy object shaders cannot add the same irradiance a second time.
            cmd.SetGlobalFloat(IrradianceValidID, 0.0f);
            cmd.SetGlobalFloat(ReprojectIrradianceID, 0.0f);
            cmd.SetGlobalFloat(DisocclusionFallbackID,
                IsFinite(settings.disocclusionFallback)
                    ? Mathf.Clamp01(settings.disocclusionFallback)
                    : 0.35f);
            cmd.SetGlobalFloat(HistoryDepthThresholdID,
                IsFinite(settings.temporalDepthThreshold)
                    ? Mathf.Max(settings.temporalDepthThreshold, 0.001f)
                    : 0.1f);
            cmd.SetGlobalMatrix(PreviousViewProjectionMatrixID, state.previousViewProjectionMatrix);
            cmd.SetGlobalMatrix(PreviousWorldToCameraMatrixID, state.previousWorldToCameraMatrix);
        }

        public override void Execute(ScriptableRenderContext context, ref RenderingData renderingData)
        {
            if (material == null) return;

            Camera cam = renderingData.cameraData.camera;
            if (!cameraStates.TryGetValue(cam.GetInstanceID(), out CameraState state)) return;
            if (state.camera == null || state.camera != cam) return;
            state.lastUsedFrame = Time.frameCount;

            CommandBuffer cmd = CommandBufferPool.Get("SSGI Pass");
            bool isNewLogicalFrame = state.lastUpdateFrame != Time.frameCount;
            Matrix4x4 projectionMatrix = cam.nonJitteredProjectionMatrix;
            bool viewChanged = !state.hasPreviousPose ||
                state.previousPosition != cam.transform.position ||
                state.previousRotation != cam.transform.rotation ||
                state.previousProjectionMatrix != projectionMatrix;
            int settingsHash = ComputeSettingsHash(settings);
            bool configurationChanged = !state.hasPreviousConfiguration ||
                state.previousSettingsHash != settingsHash;
            int rayCount = Mathf.Clamp(settings.rayCount, 1, 128);
            int baseSampleOffset = Mathf.Clamp(settings.sampleOffset, 0, 65535);
            Matrix4x4 currentWorldToCameraMatrix = renderingData.cameraData.GetViewMatrix();
            Matrix4x4 currentViewProjectionMatrix =
                renderingData.cameraData.GetGPUProjectionMatrixNoJitter() * currentWorldToCameraMatrix;

            bool projectionChanged = state.hasPreviousPose &&
                state.previousProjectionMatrix != projectionMatrix;
            bool resetHistory = configurationChanged || projectionChanged;
            if (resetHistory)
                ResetTemporalState(state);

            bool accumulate = resetHistory || isNewLogicalFrame || viewChanged;
            bool canUseHistory = accumulate && state.historyValid &&
                !resetHistory;
            // The temporal pass reprojects camera/object motion per pixel.
            // Trace samples previous irradiance at the ray-hit UV directly,
            // so disable only that multi-bounce lookup while the view moves.
            bool canUsePreviousIrradiance = canUseHistory && !viewChanged;
            if (accumulate)
            {
                if (!resetHistory && state.historyValid)
                    state.sampleOffset = (state.sampleOffset + rayCount) & 0xFFFF;
                else
                    state.sampleOffset = baseSampleOffset;
            }

            using (new ProfilingScope(cmd, ssgiProfilingSampler))
            {
                float farClip = Mathf.Max(cam.farClipPlane, 0.1f);
                float maxDistance = IsFinite(settings.maxDistance)
                    ? Mathf.Clamp(settings.maxDistance, 0.1f, farClip)
                    : Mathf.Min(4.0f, farClip);
                float thickness = IsFinite(settings.thickness)
                    ? Mathf.Clamp(settings.thickness, 0.001f, 1.0f)
                    : 0.1f;
                float originBias = IsFinite(settings.originBias)
                    ? Mathf.Clamp(settings.originBias, 0.0f, 0.1f)
                    : 0.01f;
                float intensity = IsFinite(settings.intensity)
                    ? Mathf.Clamp(settings.intensity, 0.0f, 4.0f)
                    : 1.0f;
                float blurSpread = IsFinite(settings.blurSpread)
                    ? Mathf.Clamp(settings.blurSpread, 0.0f, 8.0f)
                    : 1.5f;
                float temporalResponse = IsFinite(settings.temporalResponse)
                    ? Mathf.Clamp(settings.temporalResponse, 0.001f, 1.0f)
                    : 0.08f;
                float temporalHistoryWeight = 1.0f - temporalResponse;
                int maxHistoryFrames = Mathf.Clamp(settings.maxHistoryFrames, 2, 2048);
                float temporalDepthThreshold = IsFinite(settings.temporalDepthThreshold)
                    ? Mathf.Max(settings.temporalDepthThreshold, 0.001f)
                    : 0.1f;
                int traceWidth = state.blurA != null && state.blurA.rt != null
                    ? state.blurA.rt.width
                    : Mathf.Max(1, state.descriptor.width / (settings.halfResolution ? 2 : 1));
                int traceHeight = state.blurA != null && state.blurA.rt != null
                    ? state.blurA.rt.height
                    : Mathf.Max(1, state.descriptor.height / (settings.halfResolution ? 2 : 1));
                material.SetVector(UVToViewPosID, GIUtility.ComputeUVToViewPos(cam));
                material.SetInt(RayCountID, rayCount);
                material.SetInt(SampleOffsetID, state.sampleOffset);
                material.SetInt(MaxStepsID, Mathf.Clamp(settings.maxSteps, 1, 256));
                material.SetFloat(MaxDistanceID, maxDistance);
                material.SetFloat(ThicknessID, thickness);
                material.SetFloat(OriginBiasID, originBias);
                material.SetFloat(IntensityID, intensity);
                material.SetFloat(BlurSpreadID, blurSpread);
                material.SetFloat(HistoryDepthThresholdID, temporalDepthThreshold);
                material.SetInt(MaxHistoryFramesID, maxHistoryFrames);
                material.SetMatrix(PreviousWorldToCameraMatrixID, state.previousWorldToCameraMatrix);
                material.SetVector(TraceSizeID, new Vector4(
                    traceWidth,
                    traceHeight,
                    1.0f / Mathf.Max(1, traceWidth),
                    1.0f / Mathf.Max(1, traceHeight)));
                material.SetFloat(HalfResolutionID, settings.halfResolution ? 1.0f : 0.0f);

                if (settings.jitterDither)
                    material.EnableKeyword(JitterKeyword);
                else
                    material.DisableKeyword(JitterKeyword);

                if (settings.useHiZTracing)
                    material.EnableKeyword(HiZKeyword);
                else
                    material.DisableKeyword(HiZKeyword);

                if (settings.rngMode == SSGIRngMode.Hash)
                    material.EnableKeyword(RngHashKeyword);
                else
                    material.DisableKeyword(RngHashKeyword);

                material.SetInt(RngFrameIndexID, Mathf.Max(0, Time.frameCount & 0xFFFF));
                material.SetInt(RngSeedID, 0);

                // Keep a half-resolution copy of the current camera color. It
                // bootstraps the first frame and every frame where camera
                // motion makes the previous irradiance invalid.
                Blitter.BlitCameraTexture(cmd, sourceHandle, state.radianceRT);
                cmd.SetGlobalTexture(RadianceTextureID, state.radianceRT);

                if (accumulate)
                {
                    RTHandle previousIrradiance = canUsePreviousIrradiance
                        ? state.HistoryRead
                        : state.radianceRT;

                    // Pass 0 samples this texture at the ray hit. The first
                    // valid frame uses Camera Color; subsequent stationary
                    // frames use the accumulated irradiance history.
                    cmd.SetGlobalTexture(IrradianceTextureID, previousIrradiance);
                    cmd.SetGlobalTexture(HistoryTextureID, state.HistoryRead);
                    cmd.SetGlobalTexture(
                        HistorySampleTextureID, state.HistorySampleRead);
                    material.SetFloat(
                        PreviousIrradianceValidID,
                        canUsePreviousIrradiance ? 1.0f : 0.0f);
                    material.SetFloat(HistoryValidID, canUseHistory ? 1.0f : 0.0f);
                    material.SetFloat(HistoryWeightID, temporalHistoryWeight);

                    // SSGI -> Accumulate -> sample count -> BlurH -> BlurV.
                    // Irradiance and per-pixel sample-count histories swap in
                    // lockstep after all commands have been submitted.
                    Blitter.BlitCameraTexture(
                        cmd, previousIrradiance, state.currentIrradianceRT, material, 0);
                    Blitter.BlitCameraTexture(
                        cmd, state.currentIrradianceRT, state.blurA, material, 3);
                    Blitter.BlitCameraTexture(
                        cmd, state.currentIrradianceRT, state.HistorySampleWrite, material, 4);
                    cmd.SetGlobalTexture(
                        HistorySampleTextureID, state.HistorySampleWrite);
                    Blitter.BlitCameraTexture(cmd, state.blurA, state.blurB, material, 1);
                    Blitter.BlitCameraTexture(cmd, state.blurB, state.HistoryWrite, material, 2);
                }

                RTHandle currentIrradiance = accumulate
                    ? state.HistoryWrite
                    : state.HistoryRead;
                cmd.SetGlobalTexture(IrradianceTextureID, currentIrradiance);
                cmd.SetGlobalFloat(IrradianceValidID, state.historyValid || accumulate ? 1.0f : 0.0f);

                if (intensity > 0.0f
                    && (state.historyValid || accumulate)
                    && currentIrradiance != null && currentIrradiance.rt != null)
                {
                    int irradianceWidth = currentIrradiance.rt.width;
                    int irradianceHeight = currentIrradiance.rt.height;
                    material.SetVector(IrradianceTexelSizeID, new Vector4(
                        1.0f / Mathf.Max(1, irradianceWidth),
                        1.0f / Mathf.Max(1, irradianceHeight),
                        irradianceWidth,
                        irradianceHeight));

                    // Combine camera color and indirect diffuse into applyRT.
                    Blitter.BlitCameraTexture(cmd, sourceHandle, state.applyRT, material, 5);

                    Blitter.BlitCameraTexture(cmd, state.applyRT, sourceHandle);
                }
            }

            context.ExecuteCommandBuffer(cmd);
            CommandBufferPool.Release(cmd);

            if (accumulate)
            {
                state.historyReadIndex = 1 - state.historyReadIndex;
                state.historyValid = true;
                state.hasPreviousPose = true;
                state.previousPosition = cam.transform.position;
                state.previousRotation = cam.transform.rotation;
                state.hasPreviousConfiguration = true;
                state.previousProjectionMatrix = projectionMatrix;
                state.previousViewProjectionMatrix = currentViewProjectionMatrix;
                state.previousWorldToCameraMatrix = currentWorldToCameraMatrix;
                state.previousSettingsHash = settingsHash;
                state.lastUpdateFrame = Time.frameCount;
            }
        }

        private static void ResetTemporalState(CameraState state)
        {
            state.hasPreviousPose = false;
            state.hasPreviousConfiguration = false;
            state.historyValid = false;
            state.sampleOffset = 0;
            state.lastUpdateFrame = -1;
            state.historyReadIndex = 0;
        }

        private void RetireCameraStates(int currentCameraId)
        {
            List<int> retiredIds = new List<int>();
            foreach (KeyValuePair<int, CameraState> pair in cameraStates)
            {
                if (pair.Key != currentCameraId && pair.Value.camera == null)
                {
                    pair.Value.Release();
                    retiredIds.Add(pair.Key);
                }
            }

            foreach (int retiredId in retiredIds)
                cameraStates.Remove(retiredId);

            while (cameraStates.Count >= MaxCameraStates)
            {
                int leastRecentlyUsedId = 0;
                CameraState leastRecentlyUsed = null;
                foreach (KeyValuePair<int, CameraState> pair in cameraStates)
                {
                    if (pair.Key == currentCameraId)
                        continue;
                    if (leastRecentlyUsed == null || pair.Value.lastUsedFrame < leastRecentlyUsed.lastUsedFrame)
                    {
                        leastRecentlyUsedId = pair.Key;
                        leastRecentlyUsed = pair.Value;
                    }
                }

                if (leastRecentlyUsed == null)
                    break;

                leastRecentlyUsed.Release();
                cameraStates.Remove(leastRecentlyUsedId);
            }
        }

        private static bool IsFinite(float value)
        {
            return !float.IsNaN(value) && !float.IsInfinity(value);
        }

        private static int ComputeSettingsHash(SSGISettings value)
        {
            unchecked
            {
                int hash = 17;
                hash = hash * 31 + TemporalAlgorithmVersion;
                hash = hash * 31 + value.rayCount;
                hash = hash * 31 + value.sampleOffset;
                hash = hash * 31 + value.maxSteps;
                hash = hash * 31 + value.maxDistance.GetHashCode();
                hash = hash * 31 + value.thickness.GetHashCode();
                hash = hash * 31 + value.originBias.GetHashCode();
                hash = hash * 31 + (value.useHiZTracing ? 1 : 0);
                hash = hash * 31 + value.intensity.GetHashCode();
                hash = hash * 31 + value.blurSpread.GetHashCode();
                hash = hash * 31 + (value.jitterDither ? 1 : 0);
                hash = hash * 31 + value.temporalResponse.GetHashCode();
                hash = hash * 31 + value.maxHistoryFrames;
                hash = hash * 31 + value.temporalDepthThreshold.GetHashCode();
                hash = hash * 31 + (value.halfResolution ? 1 : 0);
                hash = hash * 31 + (int)value.rngMode;
                return hash;
            }
        }

        public override void OnCameraCleanup(CommandBuffer cmd)
        {
        }

        public void Dispose()
        {
            Shader.SetGlobalFloat(IrradianceValidID, 0.0f);
            foreach (CameraState state in cameraStates.Values)
                state.Release();
            cameraStates.Clear();
        }
    }
}
